version: '3.8'
services:
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: service-finder
