version: '3.8'
services:
  api:
    build: ./develop.Dockerfile
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: service-finder
    volumes:
      - .:/home/node/app
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: service-finder
